### ISSUE TITLE
tentative d'injection sql

### ISSUE THREAD

**Issue by DorinnB** [LotuxPunk/PunkProject#12]
des tentatives d'injection sql ont été effectuées aujourd'hui.

ne pas inserer de lignes dans la liste des donneurs dans ce cas (les stats seraient impactées)
prevenir l'injection dans la gallery

**Comment by LotuxPunk** [comment]
J'ai fais les modifs sur le serveur, je les copy paste sur le github en rentrant ;)

**Comment by LotuxPunk** [comment]
Il n'y a pas eu besoin d'insérer des choses en plus dans les fichier de par l'utilisation de `$_POST` dans la PunkGallery, dans le PunkVote, la seule entrée en `$_GET` et assurée par un `htmlspecialchars`
